# Generated by Django 3.0.3 on 2020-03-03 21:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='post_images')),
                ('caption', models.TextField(blank=True)),
                ('uploaded_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
